"""Approved assistant source registry."""

from __future__ import annotations

from grid_reliability.genai.models import SourceEntry


def source_registry() -> tuple[SourceEntry, ...]:
    common = ("executive_summary", "methodology", "incident_investigation")
    return (
        SourceEntry(
            "reports/ingestion",
            "ingestion",
            "*.md",
            "markdown",
            "governed_report",
            common,
            False,
            True,
            True,
            True,
        ),
        SourceEntry(
            "outputs/forecasting",
            "forecasting",
            "*.json",
            "json",
            "governed_metric",
            ("forecast_summary", *common),
            True,
            False,
            False,
            True,
        ),
        SourceEntry(
            "reports/forecasting",
            "forecasting",
            "*.md",
            "markdown",
            "governed_report",
            ("forecast_summary", *common),
            True,
            False,
            True,
            True,
        ),
        SourceEntry(
            "outputs/asset_health",
            "asset_health",
            "*.csv",
            "csv",
            "governed_output",
            ("asset_health", "maintenance_priority", *common),
            False,
            True,
            True,
            True,
        ),
        SourceEntry(
            "reports/asset_health",
            "asset_health",
            "*.md",
            "markdown",
            "governed_report",
            ("asset_health", "maintenance_priority", *common),
            False,
            True,
            True,
            True,
        ),
        SourceEntry(
            "outputs/outage_prediction",
            "outage_prediction",
            "*.csv",
            "csv",
            "governed_output",
            ("outage_risk", *common),
            True,
            False,
            True,
            True,
        ),
        SourceEntry(
            "reports/outage_prediction",
            "outage_prediction",
            "*.md",
            "markdown",
            "governed_report",
            ("outage_risk", *common),
            True,
            False,
            True,
            True,
        ),
        SourceEntry(
            "outputs/reliability",
            "reliability",
            "*.csv",
            "csv",
            "governed_output",
            ("reliability_performance", *common),
            False,
            True,
            True,
            True,
        ),
        SourceEntry(
            "reports/reliability",
            "reliability",
            "*.md",
            "markdown",
            "governed_report",
            ("reliability_performance", "methodology", *common),
            False,
            True,
            True,
            True,
        ),
        SourceEntry(
            "outputs/monitoring",
            "monitoring",
            "*.csv",
            "csv",
            "governed_output",
            ("monitoring_alerts", *common),
            False,
            True,
            True,
            True,
        ),
        SourceEntry(
            "reports/monitoring",
            "monitoring",
            "*.md",
            "markdown",
            "governed_report",
            ("monitoring_alerts", *common),
            False,
            True,
            True,
            True,
        ),
        SourceEntry(
            "docs",
            "documentation",
            "*.md",
            "markdown",
            "documentation",
            ("methodology", *common),
            False,
            False,
            False,
            True,
        ),
        SourceEntry(
            "configs/data_contracts",
            "contracts",
            "*.yaml",
            "yaml",
            "contract",
            ("methodology", *common),
            False,
            False,
            False,
            True,
        ),
    )
